package com.qf.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Leavebill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.id
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    private Long id;

    
    private Long days;

    
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.remark
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    private String remark;

   
    private Date leavedate;

    
    private Long state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.user_id
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    private Long userId;
    private String userName;

    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.id
     *
     * @return the value of sys_leavebill.id
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.id
     *
     * @param id the value for sys_leavebill.id
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.days
     *
     * @return the value of sys_leavebill.days
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public Long getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.days
     *
     * @param days the value for sys_leavebill.days
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public void setDays(Long days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.content
     *
     * @return the value of sys_leavebill.content
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.content
     *
     * @param content the value for sys_leavebill.content
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.remark
     *
     * @return the value of sys_leavebill.remark
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.remark
     *
     * @param remark the value for sys_leavebill.remark
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.leaveDate
     *
     * @return the value of sys_leavebill.leaveDate
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public Date getLeavedate() {
        return leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.leaveDate
     *
     * @param leavedate the value for sys_leavebill.leaveDate
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public void setLeavedate(Date leavedate) {
        this.leavedate = leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.state
     *
     * @return the value of sys_leavebill.state
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.state
     *
     * @param state the value for sys_leavebill.state
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.user_id
     *
     * @return the value of sys_leavebill.user_id
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.user_id
     *
     * @param userId the value for sys_leavebill.user_id
     *
     * @mbggenerated Tue Dec 11 21:31:32 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}